### ISSUE TITLE
doesn't recognize arrays of tables

### ISSUE THREAD

**Issue by aaronlifton3** [atom/language-toml#3]
wrong highlighting for double brackets, which represent array of tables:

``` toml
[[fruit]]
name = "apple"

[[fruit]]
name = "orange"
```
